name: ironvault
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.26+27

environment:
  sdk: ^3.9.0

dependencies:
  cunning_document_scanner: ^1.2.3
  clipboard: ^2.0.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  encrypt: ^5.0.3
  file_picker: ^10.3.6
  archive: ^4.0.7
  path: ^1.9.1
  flutter_image_compress: ^2.3.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.0.0
  http: ^1.2.2
  connectivity_plus: ^7.0.0
  local_auth: ^3.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  share_plus: ^12.0.1
  sentry_flutter: ^9.7.0
  csv: ^6.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.40
  uuid: ^4.5.2
  flutter_pdfview: ^1.4.4

dev_dependencies:
  build_runner: ^2.15.0
  drift_dev: ^2.29.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 23

flutter_native_splash:
  color: "#0B132B"
  image: assets/icon/app_icon_foreground.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  color_dark: "#0B132B"
  image_dark: assets/icon/app_icon_foreground.png

  web: false
